# Generated by scripts/new-team.sh - the only part of a team's directory
# that shouldn't be hand-edited. Each team gets a unique `key`, giving it
# a fully separate state file (and, via the DynamoDB table, a separate
# lock) from every other team. No `terraform workspace` is used here on
# purpose: workspaces share one backend config and make it too easy to
# apply against the wrong team's state by having the wrong workspace
# selected. A distinct key per directory makes cross-team blast radius
# structurally impossible, not just a matter of remembering to switch.

terraform {
  backend "s3" {
    bucket         = "acme-fintech-tfstate"
    key            = "teams/alpha/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "acme-fintech-tf-locks"
    encrypt        = true
  }
}
